# Generated by Django 3.0.3 on 2020-08-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200829_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/static/pyth_to_img/img.jpg', upload_to='images'),
        ),
    ]
